### ISSUE TITLE
The region_name folder does not direct correctly in Linux

### ISSUE THREAD

**Issue by BlueNalgene** [dominiks/uristmapsj#1]
When executing uristmaps.sh in Linux, I get an error that reads 
"00:02 ERROR: [TaskExecutor] Could not providing task for missing file: /home/ngi    nx/uristmaps/region2-01050-01-01-world_history.txt".
This error is related to executing tasks through the absolute path.  On Windows 7 machine with the exact same config and directory tree, the program works.

The files in question were placed in './region2/'; when I moved all region files (region2_.bmp and region2_.txt) files to the '.' directory, it worked.  This error suggests that there is something wrong with the way the paths work between the windows and linux boxes.

The relevant lines from the config file are:

```
base_dir = .
export = /foobar/uristmaps
# on the Windows box that line reads:
# export = C:/foobar/uristmaps  
region_name = region2
region_date = 01050-01-01
output = ${base_dir}/${region_name}/output
```

**Comment by dominiks** [comment]
I think this might a configuration issue caused by my shoddy documentation skills. When you place the region files in `./region/` your config should read:

```
base_dir = .
export = ${base_dir}/region2 # '${base_dir}/${region_name}' Should also work
region_name = region2
region_date = 01050-01-01
output = ${base_dir}/${region_name}/output
```

**Comment by BlueNalgene** [comment]
Confirmed, that solves that problem.  I successfully run the jar to produce issue #2.

**Comment by dominiks** [comment]
Good to hear.
